name: Block 'Merge branch develop' commits

on:
    push:
        branches:
            - 'release/**'

jobs:
    block_merge_commits:
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repository
                uses: actions/checkout@v2

            -   name: Check for merge commits
                run: |
                    git fetch --depth=1 origin +refs/heads/release/*:refs/remotes/origin/release/*
                    for branch in $(git for-each-ref --format='%(refname)' refs/remotes/origin/release/*); do
                      for commit in $(git log --format='%H' --reverse HEAD..$branch); do
                        if git log --format=%B -n 1 $commit | grep -Eq '^Merge branch '\''develop'\'' into release'; then
                          echo "Error: Found merge commit with message 'Merge branch 'develop' into release'."
                          exit 1
                        fi
                      done
                    done
