name: Block 'Merge branch develop' commits
on:
    pull_request:
        types: [opened, synchronize, reopened, edited]
    push:
        branches:
            - release/**

jobs:
    check-merge-message:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Check commit messages
                run: |
                    for commit in $(git log --pretty=%s HEAD^..HEAD); do
                      if [[ $commit == *"Merge branch 'develop' into release/"* ]]; then
                        echo "Error: Commit message similar to 'Merge branch 'develop' into release/' found."
                        exit 1
                      fi
                    done
